### PR TITLE
fixed small error

### PR DESCRIPTION
**Pull request by 0xflotus**

### CODE REVIEW

**Comment by vsoch** [comment]
Thanks for the fix @0xflotus ! Did you try watchme out or need any help?

I'm ready to merge, but your GitHub history looks a bit like a bot and so I need you to convince me that you aren't one first :)

**Comment by 0xflotus** [comment]
> Thanks for the fix @0xflotus ! Did you try watchme out or need any help?
> 
> I'm ready to merge, but your GitHub history looks a bit like a bot and so I need you to convince me that you aren't one first :)

I promise, I'm not a bot :D

I am browsing through some repositories to find inspiration and sometimes I find some small errors and fix them immidiately. That's all.

**Comment by vsoch** [comment]
haha, great! I really appreciate it :) Merging.

**Comment by 0xflotus** [comment]
> haha, great! I really appreciate it :) Merging.

Thanks. :)

**Pull request merged**
